keys:
  - &users: 
    - &zack age1xxlv2k00qjmw6r4fzx42mzhd7526xyj3pc6rn80l0zrp4fuanchqpu8qtd
  - &hosts:
    - &forward-onto-dawn age1clj6a2d5f6a9p66rc7qgm363eg6pf8pu92wdcxwwc3mvaxwt0q7sxjfsw8
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *zack
      - *forward-onto-dawn
