keys:
  - &in-amber-clad age13grvvydjrxnnp4dhz0zjefjyyqcpkkwv976m6krgrzxeta33vyts4fswmw
  - &forward-onto-dawn age1clj6a2d5f6a9p66rc7qgm363eg6pf8pu92wdcxwwc3mvaxwt0q7sxjfsw8
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *in-amber-clad
      - *forward-onto-dawn
